import type { Metadata } from "next";
import { Assistant } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import GlobalProvider from "@/components/app/GlobalProvider";

const assistantFont = Assistant({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${assistantFont.className} antialiased`}>
        <GlobalProvider>{children}</GlobalProvider>

        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
